"use strict";function numberFormat(value,decimals,decPoint,thousandsSep){var decPoint=decPoint||'.',decimals=(decimals!==undefined?decimals:2),thousandsSep=thousandsSep||' ';if(typeof value==='string'){value=parseFloat(value);}
let result=value.toLocaleString('en-US',{maximumFractionDigits:decimals,minimumFractionDigits:decimals});let pieces=result.split('.');pieces[0]=pieces[0].split(',').join(thousandsSep);return pieces.join(decPoint);}
function leadZero(n){if(n){return(n<10?'0':'')+n;}else{return '00';}}
if(!Date.now){Date.now=function(){return new Date().getTime();}}
function calcMoneyByLang(money,curs,lang){return money;}
function setEqualHeight(columns){var tallestcolumn=0;columns.each(function(){var currentHeight=$(this).height();if(currentHeight>tallestcolumn){tallestcolumn=currentHeight;}});columns.height(tallestcolumn);}
function footerToBottom(){if(jQuery(window).height()>jQuery("body").height()){jQuery("main").innerHeight(jQuery(window).height()-jQuery("header").innerHeight()-jQuery("footer").innerHeight());}}
function initScrollBar(content,arg,hide){const bars='.jspHorizontalBar, .jspVerticalBar';if(hide===true){content.bind('jsp-initialised',function(event,isScrollable){jQuery(this).find(bars).hide();}).jScrollPane(arg).hover(function(){jQuery(this).find(bars).stop().fadeTo('fast',0.9);},function(){jQuery(this).find(bars).stop().fadeTo('fast',0);});}else{content.jScrollPane(arg);}}
jQuery(document).ready(function(){if(typeof(popUpLogin)!=='undefined'&&popUpLogin){jQuery("#login").modal("show");}
var io=jQuery('#io');if(io.is('input'))io.on('change',changeTypeSkin);});jQuery(window).ready(function(){});function changeTypeSkin(){var io=jQuery('#io');jQuery.ajax({url:"/ajax.php",method:"POST",data:{"csrf-token":io.data('csrf'),"ajax-token":io.data('ajax'),"user":io.data('user'),"slim":io.prop('checked')},success:function(data){},error:function(xhr,ajaxOptions,thrownError){}});}
function logout(msg){var io=jQuery('#io');if(confirm(msg)===true){jQuery.ajax({url:"/ajax.php",method:"POST",data:{"csrf-token":io.data('csrf'),"ajax-token":io.data('ajax'),"user":io.data('user'),"exit":io.data('user')},success:function(data){if(data.result===true){document.location.href='/';}}});}
return false;}
$(()=>{if(!ko.isObservable(tlVM.portion))tlVM.portion=ko.observable(0);if(!ko.isObservable(tlVM.ajaxProgress))tlVM.ajaxProgress=ko.observable(false);if((tlVM||{}).viewMode==='scroll'){let div=$('#ajax');div.appear({force_process:true});div.on('appear',e=>{if((pagination.pageNow+tlVM.portion())<pagination.numPages){setTimeout(ajaxLoadArticles,100);}});}});function ajaxLoadArticles(e){if(tlVM.ajaxProgress())return;tlVM.ajaxProgress(true);tlVM.portion(tlVM.portion()+1);jQuery.ajax({url:window.location.href,method:"POST",data:{"portion":tlVM.portion(),"pagination":pagination,},success:function(data){jQuery.ajax({url:window.location.href,method:"POST",data:{"portion":tlVM.portion(),"pagination":pagination,"paginationBlock":true,},success:function(pData){$('.pagination-block').html(pData);let url,page=pagination.pageNow+tlVM.portion();if(pagination.pageNow===1&&tlVM.portion()===1){url=location.href+'2/';document.title=document.title+' - 2';}else{url=location.href.replace(/\/\d+\//g,'/'+page+'/');document.title=document.title.replace(/\d+$/g,page);}
window.history.pushState({},null,url);}});$('#ajax').before(data);},complete:()=>{tlVM.ajaxProgress(false);}});}